#!/usr/bin/env bash

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Start gnome keyring
exec gnome-keyring-daemon --daemonize --start --components=gpg,pkcs11,secrets,ssh &

# Polkit agent
# if [[ ! `pidof xfce-polkit` ]]; then
# 	/usr/lib/xfce-polkit/xfce-polkit &
# fi
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

pipewire &
# Set wallpaper
swww-daemon &

# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &
# ags &

# Start network manager applet
nm-applet --indicator &

# Start mpd
exec mpd &

# clipboard history
exec wl-paste --watch cliphist store
